# Generated by Django 5.1.6 on 2025-03-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addsong',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
