# Generated by Django 5.1.6 on 2025-04-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsl', '0002_addsong_click_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='addsong',
            name='genre',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
